### ISSUE TITLE
Adding support for Python

### ISSUE THREAD

**Issue by seacowx** [Jean-Tinland/vscode-theme-day-shift#1]
Hi Jean, thank you for making such an outstanding theme. I'm wondering if you would consider adding support for Python. I am a heavy python user and I really wish to use the day shift theme (which I'm already using in iterm2) in vs code.

**Comment by Jean-Tinland** [comment]
Sure! I published an update that includes a better handling of Python syntax! Please let me know if I can improve the colorization in any way!

And thank you for your message, I'm glad this theme pleases you.

**Comment by seacowx** [comment]
Thank you for the speedy adaptation! The python code under the day shift theme looks stunning! Please accept my apology for making additional request but I am also wondering if you would kindly do the same adaptation to the night shift theme. Thank you again for making these amazing tools/themes : )

**Comment by Jean-Tinland** [comment]
You are welcome!
No problem at all, I'm more than willing to improve theses theme so I'll take any pertinent suggestions!
I added Python support in night-shift theme. The syntax highlight should be similar to day-shift. Please let me know if the outcome is satisfying!

**Comment by seacowx** [comment]
Just tried the new night-shift theme and it looks amazing with Python! Thank you Jean 🤗
